# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for OPPO fingerprint drivers (SDM660 4.19 port)
#

obj-$(CONFIG_OPPO_FINGERPRINT) += oppo_fp_common/
obj-$(CONFIG_OPPO_FINGERPRINT) += fpc/
obj-$(CONFIG_OPPO_FINGERPRINT) += goodix_fp/
