# VENDOR_EDIT
# Goodix optical fingerprint driver Makefile - QCOM/SDM660 only

DEFS = -DCONFIG_OPPO_FINGERPRINT_KERNEL_VER=$(VERSION)
ccflags-y += $(DEFS)

obj-y  += gf_spi.o gf_platform.o gf_netlink.o
