#
# Makefile for the Synaptics touchscreen drivers.
#

obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_S3508) += S3508/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_S3320) += S3320/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_S3706) += S3706/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS) += synaptics_touch_panel_remote.o
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS) += synaptics_common.o
